- name: Install java
  apt:
    name:
      - openjdk-8-jdk
    state: present

- name: Create Jenkins group
  group:
    name: "{{ jenkins_group }}"
    state: present

- name: Create Jenkins user
  user:
    name: "{{ jenkins_owner }}"
    group: "{{ jenkins_group }}"
    home: "{{ jenkins_home }}"
    shell: "/bin/false"
    state: present

- name: Add Jenkins/Docker key
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "https://download.docker.com/linux/ubuntu/gpg"
    - "https://pkg.jenkins.io/debian-stable/jenkins.io.key"

- name: Add Jenkins/Docker repository
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://pkg.jenkins.io/debian-stable binary/"
    - "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"

- name: Install Jenkins/Docker package
  apt:
    name: "{{ item }}"
    force: yes
    update_cache: yes
  with_items:
    - "jenkins={{ jenkins_version }}"
    - "docker-ce"

- name: Add Jenkins user to docker group
  user:
    name: jenkins
    groups: docker
    append: yes

- name: Make sure configuration file is up to date (config.xml)
  copy:
    src: "global-config.xml"
    dest: "{{ jenkins_home }}/config.xml"
    mode: 0644
    owner: "{{ jenkins_owner }}"
    group: "{{ jenkins_group }}"


- name: Set JENKINS_HOME
  lineinfile:
    dest: /etc/default/jenkins
    line: "JENKINS_HOME={{ jenkins_home }}"
    regexp: '^JENKINS_HOME='

- name: Set Jenkins port
  lineinfile:
    dest: /etc/default/jenkins
    regexp: '^HTTP_PORT='
    line: "HTTP_PORT={{ jenkins_port }}"

- name: Set Jenkins command line options
  lineinfile:
    dest: /etc/default/jenkins
    regexp: '^JAVA_ARGS='
    line: "JAVA_ARGS=\"{{ jenkins_java_opts }}\""

- name: Add pre-configured jobs
  copy:
    src: "jobs/"
    dest: "{{ jenkins_home }}/jobs/"
    mode: 0777
    directory_mode: 0777
    owner: "{{ jenkins_owner }}"
    group: "{{ jenkins_group }}"

- name: Restart & Enable Jenkins
  systemd:
    name: jenkins
    state: restarted
    enabled: true

- name: Waiting for jenkins to restart
  pause:
    minutes: 1
