
---
- name: Get token for Jenkins API
  uri:
    url: 'http://{{ ansible_host }}:{{ jenkins_port }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'
    return_content: yes
    status_code: 200,404
  register: jenkins_token_result
  until: jenkins_token_result.status == 200 or jenkins_token_result.status == 404
  retries: 5
  delay: 1

- name: Install plugins
  uri:
    url: "http://{{ ansible_host }}:{{ jenkins_port }}/pluginManager/installNecessaryPlugins"
    method: POST
    headers:
      Content-Type: "text/xml"
      Jenkins-Crumb: "{{ jenkins_token_result.content.split(':')[1] | default('noCrumb') }}"
    body: "<jenkins><install plugin=\"{{ item }}@latest\" /></jenkins>"
    status_code: 200,302
  with_items: "{{ jenkins_plugins }}"
  when: jenkins_token_result.status == 200
